LPページ追加
commew/timelogger-web pull request #136
Opened 2023-10-11 02:49 UTC by ai-ura

# issueURL

#91 

# この PR で対応する範囲 / この PR で対応しない範囲

- LP用のファイルを追加しました。

# Storybook の URL、 スクリーンショット

なし

# 変更点概要

- [timelogger-lp](https://github.com/commew/timelogger-lp) で作成したトップページLPのファイルを追加しました。
  - timelogger-lp/public 内の全ファイルになります。 

# レビュアーに重点的にチェックして欲しい点

コーディング内容は確認済みです。
リリースをお願いいたします。

# 補足情報

特にありません。

2023-10-11 04:38 UTC, keitakn requested changes
@ai-ura 

PRありがとうございます！

以下ご確認頂けますか？？

# このPRは課題の完了条件を満たしていない

本件は https://github.com/commew/timelogger-web/issues/91 を解決するためのPRだと思われますが、このブランチをローカルに落として `/` にAccessしたところ仮のトップページが表示されました。


<img width="1248" alt="スクリーンショット 2023-10-11 13 32 16" src="https://github.com/commew/timelogger-web/assets/11032365/87691069-443c-43cd-9dfb-8f62b16b50be">

https://github.com/commew/timelogger-web/blob/main/.github/PULL_REQUEST_TEMPLATE.md のテンプレートに従い、このPRで対応すること、しないことを明確に記載して頂けますか？

（そもそも何ですが /public にindex.htmlがないのでページの表示も出来ないのでは？と思います）

# CIが失敗しているのでご確認をお願いします

https://github.com/commew/timelogger-web/actions/runs/6477369572/job/17587458612

<img width="982" alt="スクリーンショット 2023-10-11 13 34 40" src="https://github.com/commew/timelogger-web/assets/11032365/b2de956b-50d0-4db0-88d7-bfd3967c28f8">

`prettier` で整形されていないファイルがコミットされているからだと思われます、本リポジトリのREADMEを見ながら `npm run format` を実行するか、もしくは修正が難しいようであれば、以下のファイルに `/public` を追加してLinterやformatterの対象範囲外となるようにして頂きたいです↓

- `.prettierignore`
- `.eslintignore`

2023-10-12 03:05 UTC, ai-ura commented
@keitakn 

ご確認とご指摘ありがとうございました。

ファイルの追加とチェッカーの範囲外になる修正をしてアップしたのですが、
まだ next.config.js  の設定ができていないので、全部終わった時点でご連絡します。

2023-10-12 04:51 UTC, keitakn commented
@ai-ura 承知しました！ありがとうございます！

2023-10-12 07:45 UTC, keitakn commented
@ai-ura @y-uchiida 

ちょっと自分のローカルで試してみたのですが `next.config.js` を以下のようにすると `/` でやっても `rewrites` が有効にならないのですが https://github.com/commew/timelogger-web/blob/main/src/pages/index.tsx を削除したら問題なく表示されました！

どうもpages配下に `index.tsx` があるとそっちが優先して表示されるっぽいですね。

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  rewrites: async () => {
    return [
      {
        source: '/',
        destination: '/index.html',
      },
    ];
  },
}

module.exports = nextConfig
```

<img width="1128" alt="スクリーンショット 2023-10-12 16 43 38" src="https://github.com/commew/timelogger-web/assets/11032365/20173e5b-57f6-4e6a-b50e-4f27af72dcdd">

なので https://github.com/commew/timelogger-web/blob/main/src/pages/index.tsx を削除して `next.config.js` を私が提示した内容に変更して頂ければ本件の完了の定義は満たせると思います！

2023-10-12 08:06 UTC, ai-ura commented
@keitakn @y-uchiida 

ありがとうございます！！
「connect ECONNREFUSED」というエラーが直せなくて悩んでいたのですが、
keitaさんに試していただいた方法で、私の方でもローカルで確認ができました。

next.config.js に設定を追加し、 src/pages/index.tsx ファイルを削除してPushしましたので、
改めてご確認をお願いいたします！

2023-10-12 09:06 UTC, keitakn commented on public/index.html
> +    <title>timmew</title>
![badge](https://img.shields.io/badge/review-imo-orange.svg)

このページは検索エンジンにインデックスされる唯一のページなので `description` タグあたりはあったほうが良い気がします、このPRの目的とは異なるので、https://github.com/commew/timelogger-web/issues/31 と合わせて `description` タグや構造化データの追加等も検討しても良いかと思いますがいかがでしょうか👀？

2023-10-12 09:10 UTC, keitakn commented on public/index.html
> +    <title>timmew</title>
↑の件は https://github.com/commew/timelogger-web/issues/31  でやったほうが良いのでコメント書いておきました！

https://github.com/commew/timelogger-web/issues/31#issuecomment-1759227373

2023-10-12 12:23 UTC, keitakn approved these changes
ご対応ありがとうございます！

マージして頂ければと思います👍

[![LGTMeow](https://lgtm-images.lgtmeow.com/2022/03/23/10/9738095a-f426-48e4-be8d-93f933c42917.webp)](https://lgtmeow.com)

2023-10-12 12:29 UTC, merged

2023-10-12 12:31 UTC, ai-ura commented
再三のご確認ありがとうございました。マージいたしました！

2023-10-12 17:16 UTC, y-uchiida commented
本日不在にしていて、確認できずすみませんでした！
お二人ともご対応いただきありがとうございました！